#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Fri Dec  5 18:18:13 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((735, 818))
        self.SetTitle("frame")
        self.SetBackgroundColour(wx.Colour(255, 0, 0))
        
        self.subtotal=0
        self.adulto=0
        self.menores=0
        selfinformacion=""
        self.horarioSeleccionado=""

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("C:/Users/minec/Desktop/werooooo/R.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, wx.ALIGN_CENTER, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        label_1.SetMinSize((43, 16))
        label_1.SetFont(wx.Font(9, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("C:/Users/minec/Desktop/werooooo/R.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_2.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula:")
        grid_sizer_2.Add(label_2, 0, 0, 0)

        self.cbmPelicula = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        grid_sizer_2.Add(self.cbmPelicula, 0, 0, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("C:/Users/minec/Desktop/werooooo/Jurasicc Word.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bitmap_3, 0, 0, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala:")
        grid_sizer_3.Add(label_3, 0, 0, 0)

        self.lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "----------")
        grid_sizer_3.Add(self.lbSala, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(1, 3, 0, 0)
        sizer_2.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario:")
        grid_sizer_4.Add(label_5, 0, 0, 0)

        grid_sizer_8 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_4.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        self.rbHorario1 = wx.RadioButton(self.panel_1, wx.ID_ANY, "17:00")
        grid_sizer_8.Add(self.rbHorario1, 0, 0, 0)

        self.rbHorario3 = wx.RadioButton(self.panel_1, wx.ID_ANY, "18:00")
        grid_sizer_8.Add(self.rbHorario3, 0, 0, 0)

        self.rbHorario2 = wx.RadioButton(self.panel_1, wx.ID_ANY, "20:00")
        grid_sizer_4.Add(self.rbHorario2, 0, 0, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos")
        sizer_2.Add(label_6, 0, 0, 0)

        grid_sizer_6 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Adulto($80:")
        grid_sizer_6.Add(label_7, 0, 0, 0)

        self.tfAdultos = wx.TextCtrl(self.panel_1, wx.ID_ANY, "",style=wx.TE_PROCESS_ENTER)
        grid_sizer_6.Add(self.tfAdultos, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Menores($70):")
        grid_sizer_5.Add(label_8, 0, 0, 0)

        self.tfMenores = wx.TextCtrl(self.panel_1, wx.ID_ANY, "",style=wx.TE_PROCESS_ENTER)
        grid_sizer_5.Add(self.tfMenores, 0, 0, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:")
        sizer_2.Add(self.lbSubtotal, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar\n")
        grid_sizer_7.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente\n")
        grid_sizer_7.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.cbmPelicula.Bind(wx.EVT_COMBOBOX, self.SelecciondePelicula)
        self.rbHorario1.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario1)
        self.rbHorario3.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario3)
        self.rbHorario2.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario2)
        self.tfAdultos.Bind(wx.EVT_TEXT_ENTER, self.sumarAdultos)
        self.tfMenores.Bind(wx.EVT_TEXT_ENTER, self.sumarMenores)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarTaquilla)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVenta)
        # end wxGlade
    def cargar_imagen(self,ruta):
        bitmap=wx.Bitmap(ruta,wx.BITMAP_TYPE_ANI)
        self.cbmPelicula.SetBitmap(bitmap)
        
    def SelecciondePelicula(self, event):  # wxGlade: MyFrame.<event_handler>
        pelicula=self.cbmPelicula.GetValue()
        imagen=""
        sala=""
        horario1=horario2=horario3=""
        print(f"Pelicula seleccionada: {pelicula}")

        if pelicula == "Jurasicc Word":
            imagen = "Jurasicc Word.jpg"
            sala = "1"
            horario1 = "14:00"
            horario2 = "17:00"
            horario3 = "20:00"

        elif pelicula == "Superman":
            imagen = "Superman.jpg"
            sala = "2"
            horario1 = "13:30"
            horario2 = "16:30"
            horario3 = "19:30"

        elif pelicula == "Grinch":
            imagen = "Grinch.png"
            sala = "3"
            horario1 = "15:00"
            horario2 = "18:00"
            horario3 = "21:00"

        self.cargar_imagen(imagen)
        self.lbSala.SetLabel(sala)
        self.rbHorario1.SetLabel(horario1)
        self.rbHorario2.SetLabel(horario2)
        self.rbHorario3.SetLabel(horario3)

        self.informacion = f"Pelicula: {pelicula} \n Sala: {sala}"
        print(f"Listo para disfrutar de \n {self.informacion}")

        event.Skip()
   
    def seleccionHorario1(self, event):  # wxGlade: MyFrame.<event_handler>
        self.horarioSeleccionado=self.rbHorario1.GetLabelText()
        event.Skip()

    def seleccionHorario3(self, event):  # wxGlade: MyFrame.<event_handler>
        self.horarioSeleccionado=self.rbHorario2.GetLabelText()
        event.Skip()

    def seleccionHorario2(self, event):  # wxGlade: MyFrame.<event_handler>
        self.horarioSeleccionado=self.rbHorario3.GetLabelText()
        event.Skip()

    def sumarAdultos(self, event):  # wxGlade: MyFrame.<event_handler>
        try:
         self.adultos = int(self.tfAdultos.GetValue())   # Obtiene el valor de adultos
         subtotal_a = self.adultos * 80                  # Precio por adulto
         self.subtotal = subtotal_a                      # Guarda el subtotal
         self.lbSubtotal.SetLabel(f"Subtotal: ${subtotal_a:.2f}")  # Muestra subtotal
        except ValueError:
         wx.MessageBox("Por favor ingresa un número válido", "Error", wx.OK | wx.ICON_ERROR)
        event.Skip()
 
    def sumarMenores(self, event):  # wxGlade: MyFrame.<event_handler>
        try:
         self.menores = int(self.tfMenores.GetValue())   # Obtiene el valor de menores
         subtotal_b = self.menores * 70                  # Precio por menor
         self.subtotal = (self.adultos * 80) + subtotal_b  # Suma subtotales
         self.lbSubtotal.SetLabel(f"Subtotal: ${self.subtotal:.2f}")  # Muestra subtotal
        except ValueError:
         wx.MessageBox("Por favor ingresa un número válido", "Error", wx.OK | wx.ICON_ERROR)
         event.Skip()      

    def limpiarValores_campos(self):
       self.subtotal=0
       self.adultos=0
       self.menores=0
       self.informacion=""
       self.horarioSeleccionado=""
       
       
       self.cargar_imagen("logo.jpg")
       self.rbHorario1.SetLabel("00:00")
       self.rbHorario2.SetLabel("00:00")
       self.rbHorario3.SetLabel("00:00")
       self.rbHorario1.SetValue("False")
       self.rbHorario2.SetValue("False")
       self.rbHorario3.SetValue("False")
       self.cbmPelicula.SetSelection(wx.NOT_FOUND)
       self.lbSala.SetLabel("---")
       self.tfAdultos.SetValue("0")
       self.tfMenores.SetValue("0")
       self.lbSubtotal.SetLabel("0")
    event.Skip()

    def limpiarTaquilla(self, event):  # wxGlade: MyFrame.<event_handler>
        self.limpiarValores_campos()
        event.Skip()

    def siguienteVenta(self, event):  # wxGlade: MyFrame.<event_handler> 
        self.informacion = f"{self.informacion} \n horario:{self.horarioSeleccionado}"
        self.informacion = f"{self.informacion} \n adultos:{self.adultos}\n Menores de 12 años :{self.menores}"
        self.informacion = f"{self.informacion} \n Subtotal:{self.subtotal}"
        pregunta = wx.MessageDialog(
        self,
        f"Confirmación de Taquilla.\n"
        f"Está seguro que desea confirmar la venta?\n\n{self.informacion}",
        "Taquilla",
        style=wx.YES_NO | wx.ICON_QUESTION
        )

        respuesta = pregunta.ShowModal()
        pregunta.Destroy()
        
        if respuesta == wx.ID_YES:
         print("Venta cancelada")
         self.limpiarValores_campos()
        elif respuesta ==wx.ID_NO:
         self.limpiarValores_campos()
         event.Skip()

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
